package com.mycompany.minipc.gui;

/**
 * Ventana principal del simulador Mini PC.
 *
 * PRUEBA DE FORMATO. Esta version reducida existe solo para verificar que
 * el disenador visual de NetBeans acepta el par .java/.form generado a
 * mano. Cubre los cinco tipos de layout y los editores de propiedades que
 * usa el diseno completo: BorderLayout, BoxLayout, FlowLayout, GridLayout,
 * JSplitPane, JScrollPane, bordes con titulo y fuentes monoespaciadas.
 *
 * Todavia no implementa VistaPrincipal ni conecta el controlador.
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Crea la ventana principal.
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        tbBarra = new javax.swing.JToolBar();
        btnCargar = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        sepAcciones = new javax.swing.JToolBar.Separator();
        btnConfig = new javax.swing.JButton();
        pnlContexto = new javax.swing.JPanel();
        lblArchivo = new javax.swing.JLabel();
        lblArchivoValor = new javax.swing.JLabel();
        spPrincipal = new javax.swing.JSplitPane();
        pnlInstrucciones = new javax.swing.JPanel();
        scrInstrucciones = new javax.swing.JScrollPane();
        tblInstrucciones = new javax.swing.JTable();
        spSecundario = new javax.swing.JSplitPane();
        pnlMemoria = new javax.swing.JPanel();
        scrMemoria = new javax.swing.JScrollPane();
        tblMemoria = new javax.swing.JTable();
        pnlBCP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPcValor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIrBinValor = new javax.swing.JLabel();
        pnlConsola = new javax.swing.JPanel();
        scrConsola = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini PC - Simulador del ciclo de instruccion");
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlSuperior.setLayout(new javax.swing.BoxLayout(pnlSuperior, javax.swing.BoxLayout.Y_AXIS));

        tbBarra.setFloatable(false);
        tbBarra.setRollover(true);

        btnCargar.setText("Cargar .asm");
        btnCargar.setToolTipText("Selecciona un archivo de codigo ensamblador");
        btnCargar.setFocusable(false);
        tbBarra.add(btnCargar);

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.setToolTipText("Ejecuta el programa completo de forma automatica");
        btnEjecutar.setEnabled(false);
        btnEjecutar.setFocusable(false);
        tbBarra.add(btnEjecutar);
        tbBarra.add(sepAcciones);

        btnConfig.setText("Configurar");
        btnConfig.setToolTipText("Tamano de memoria, limite de kernel y velocidad");
        btnConfig.setFocusable(false);
        tbBarra.add(btnConfig);

        pnlSuperior.add(tbBarra);

        pnlContexto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblArchivo.setText("Archivo:");
        pnlContexto.add(lblArchivo);

        lblArchivoValor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblArchivoValor.setText("(ninguno)");
        pnlContexto.add(lblArchivoValor);

        pnlSuperior.add(pnlContexto);

        getContentPane().add(pnlSuperior, java.awt.BorderLayout.NORTH);

        spPrincipal.setDividerLocation(380);
        spPrincipal.setOneTouchExpandable(true);

        pnlInstrucciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrucciones"));
        pnlInstrucciones.setLayout(new java.awt.BorderLayout());

        tblInstrucciones.setRowHeight(22);
        scrInstrucciones.setViewportView(tblInstrucciones);

        pnlInstrucciones.add(scrInstrucciones, java.awt.BorderLayout.CENTER);

        spPrincipal.setLeftComponent(pnlInstrucciones);

        spSecundario.setDividerLocation(330);

        pnlMemoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Memoria"));
        pnlMemoria.setLayout(new java.awt.BorderLayout());

        tblMemoria.setRowHeight(22);
        scrMemoria.setViewportView(tblMemoria);

        pnlMemoria.add(scrMemoria, java.awt.BorderLayout.CENTER);

        spSecundario.setLeftComponent(pnlMemoria);

        pnlBCP.setBorder(javax.swing.BorderFactory.createTitledBorder("BCP actual - CPU 1"));
        pnlBCP.setLayout(new java.awt.GridLayout(0, 2, 8, 4));

        jLabel1.setText("PC:");
        pnlBCP.add(jLabel1);

        lblPcValor.setText("-");
        pnlBCP.add(lblPcValor);

        jLabel2.setText("IR (binario):");
        pnlBCP.add(jLabel2);

        lblIrBinValor.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lblIrBinValor.setText("-");
        pnlBCP.add(lblIrBinValor);

        spSecundario.setRightComponent(pnlBCP);

        spPrincipal.setRightComponent(spSecundario);

        getContentPane().add(spPrincipal, java.awt.BorderLayout.CENTER);

        pnlConsola.setBorder(javax.swing.BorderFactory.createTitledBorder("Consola"));
        pnlConsola.setLayout(new java.awt.BorderLayout());

        txtConsola.setEditable(false);
        txtConsola.setColumns(20);
        txtConsola.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtConsola.setLineWrap(true);
        txtConsola.setRows(6);
        scrConsola.setViewportView(txtConsola);

        pnlConsola.add(scrConsola, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConsola, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Arranque temporal para probar la ventana de forma aislada.
     *
     * @param args no se usan
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblArchivoValor;
    private javax.swing.JLabel lblIrBinValor;
    private javax.swing.JLabel lblPcValor;
    private javax.swing.JPanel pnlBCP;
    private javax.swing.JPanel pnlConsola;
    private javax.swing.JPanel pnlContexto;
    private javax.swing.JPanel pnlInstrucciones;
    private javax.swing.JPanel pnlMemoria;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JScrollPane scrConsola;
    private javax.swing.JScrollPane scrInstrucciones;
    private javax.swing.JScrollPane scrMemoria;
    private javax.swing.JToolBar.Separator sepAcciones;
    private javax.swing.JSplitPane spPrincipal;
    private javax.swing.JSplitPane spSecundario;
    private javax.swing.JTable tblInstrucciones;
    private javax.swing.JTable tblMemoria;
    private javax.swing.JToolBar tbBarra;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables
}
